// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIuV-WC2crKNyEDO4_KPPvmtk6nFyH9Cc',
    appId: '1:830207006839:web:02f3f90017117bc6180e72',
    messagingSenderId: '830207006839',
    projectId: 'concerttickets-fdb80',
    authDomain: 'concerttickets-fdb80.firebaseapp.com',
    storageBucket: 'concerttickets-fdb80.appspot.com',
    measurementId: 'G-LP0WB1SS8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD30tsIBQVfCi1W7CSh2UVZP7THD2I1FyM',
    appId: '1:830207006839:android:bfcd40b641104ed8180e72',
    messagingSenderId: '830207006839',
    projectId: 'concerttickets-fdb80',
    storageBucket: 'concerttickets-fdb80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC60APcxalSRRFZsczjtSf-lOfKD06PPag',
    appId: '1:830207006839:ios:6a9a604104da1ed9180e72',
    messagingSenderId: '830207006839',
    projectId: 'concerttickets-fdb80',
    storageBucket: 'concerttickets-fdb80.appspot.com',
    iosBundleId: 'com.example.concertTickets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC60APcxalSRRFZsczjtSf-lOfKD06PPag',
    appId: '1:830207006839:ios:46912c3e43fc3e49180e72',
    messagingSenderId: '830207006839',
    projectId: 'concerttickets-fdb80',
    storageBucket: 'concerttickets-fdb80.appspot.com',
    iosBundleId: 'com.example.concertTickets.RunnerTests',
  );
}
